# Permalinks
#
permalink:           pretty

# Setup
title:               VISTA Data Project 
tagline:             Master Data Management for VA VISTA
url:                 http://vistadataproject.info
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              conordowling
  email:             conor-dowling@caregraf.com

# Custom vars
github:
  repo:              https://github.com/vistadataproject/vistadataproject.github.io

markdown: kramdown
kramdown:
  input: GFM

gems: [jekyll-paginate]
